/**
 * XTen National Directory & People Portal - Sample Dataset
 * Synchronized with Australian Business Register (ABR) & ASIC Data Model
 */

const PURCHASABLE_FEATURES = [
  {
    id: "featured",
    name: "Featured Listing",
    price_monthly: "$29",
    price_period: "per month (or $290/yr)",
    badge: "FEATURED",
    badge_color: "amber",
    popular: false,
    tagline: "Top of category ranking & verified credibility for local businesses.",
    features: [
      "Priority placement above standard registry listings in your category & suburb",
      "Distinctive golden 'Featured Business' card highlight",
      "Official 'Verified Entity' trust seal & ATO Modulo-89 certificate",
      "Direct link to your company website & social channels (SEO Dofollow)",
      "Direct telephone click-to-call & enquiry button",
      "Up to 3 UNSPSC product & service categories — buyers searching for what you do find you; choose a category group and every service beneath it is included",
      "Monthly visitor search & impression telemetry report"
    ]
  },
  {
    id: "prominent",
    name: "Prominent Listing",
    price_monthly: "$59",
    price_period: "per month (or $590/yr)",
    badge: "MOST POPULAR",
    badge_color: "blue",
    popular: true,
    tagline: "Maximum visibility, search dominance, and exclusive lead capture.",
    features: [
      "Guaranteed Top 3 placement across your entire ANZSIC division & postcode",
      "Competitor ad exclusion (no rival businesses advertised on your profile)",
      "Direct Lead Enquiry Form delivering customer requests straight to your inbox",
      "High-contrast card highlight with animated spotlight badge",
      "Full business description, products, operating hours & team directory",
      "Priority inclusion in regional buyer email digests",
      "Up to 5 UNSPSC product & service categories (category groups cover everything beneath them), shown first when a buyer searches those services in your state",
      "Includes all features of the Featured tier"
    ]
  },
  {
    id: "video_showcase",
    name: "30-Sec Video Showcase",
    price_monthly: "$19",
    price_period: "per month (Add-on or $39 standalone)",
    badge: "3X ENGAGEMENT",
    badge_color: "purple",
    popular: false,
    tagline: "Engage visitors with an authentic 30-second video introduction.",
    features: [
      "Up to 30-second HD video embedded directly on your public profile",
      "Video play badge in search results (proven 3x higher click-through rate)",
      "Showcase your facilities, clinical practice, workshop, or team message",
      "Custom video thumbnail, call-to-action button, and captions support",
      "Hosted on high-speed Australian edge CDN with zero competitor ads",
      "Easily updated anytime via your verified owner dashboard"
    ]
  }
];

const ANZSIC_DIVISIONS = [
  { code: "A", name: "Agriculture, Forestry & Fishing", icon: "🌾", count: "84k", slug: "agriculture" },
  { code: "B", name: "Mining & Resources", icon: "⛏️", count: "18k", slug: "mining" },
  { code: "C", name: "Manufacturing", icon: "🏭", count: "142k", slug: "manufacturing" },
  { code: "D", name: "Electricity, Gas & Water", icon: "⚡", count: "12k", slug: "utilities" },
  { code: "E", name: "Construction & Trades", icon: "🏗️", count: "485k", slug: "construction" },
  { code: "F", name: "Wholesale Trade", icon: "📦", count: "116k", slug: "wholesale" },
  { code: "G", name: "Retail Trade", icon: "🛍️", count: "235k", slug: "retail" },
  { code: "H", name: "Accommodation & Food", icon: "☕", count: "178k", slug: "hospitality" },
  { code: "I", name: "Transport & Logistics", icon: "🚚", count: "165k", slug: "transport" },
  { code: "J", name: "IT, Software & Media", icon: "💻", count: "98k", slug: "technology" },
  { code: "K", name: "Financial & Insurance", icon: "🏦", count: "290k", slug: "finance" },
  { code: "L", name: "Rental & Real Estate", icon: "🏢", count: "280k", slug: "real-estate" },
  { code: "M", name: "Professional & Technical", icon: "⚖️", count: "410k", slug: "professional" },
  { code: "N", name: "Administrative & Support", icon: "📋", count: "155k", slug: "administrative" },
  { code: "P", name: "Education & Training", icon: "🎓", count: "52k", slug: "education" },
  { code: "Q", name: "Health Care & Medical", icon: "🏥", count: "260k", slug: "healthcare" },
  { code: "R", name: "Arts & Recreation", icon: "🎨", count: "45k", slug: "arts" },
  { code: "S", name: "Other Personal Services", icon: "🔧", count: "185k", slug: "other-services" }
];

const POPULAR_HUBS = [
  { state: "NSW", name: "Sydney", postcode: "2000" },
  { state: "NSW", name: "Parramatta", postcode: "2150" },
  { state: "VIC", name: "Melbourne", postcode: "3000" },
  { state: "VIC", name: "Dandenong", postcode: "3175" },
  { state: "VIC", name: "Ballarat", postcode: "3350" },
  { state: "QLD", name: "Brisbane", postcode: "4000" },
  { state: "QLD", name: "Gold Coast", postcode: "4217" },
  { state: "WA", name: "Perth", postcode: "6000" },
  { state: "WA", name: "Fremantle", postcode: "6160" },
  { state: "SA", name: "Adelaide", postcode: "5000" },
  { state: "TAS", name: "Hobart", postcode: "7000" },
  { state: "ACT", name: "Canberra", postcode: "2601" },
  { state: "NT", name: "Darwin", postcode: "0800" }
];

const DIRECTORY_DATA = {
  companies: [
    {
      id: "comp-xten-1",
      abn: "38602365346",
      acn: "602365346",
      name: "XTen Systems Pty Ltd",
      trading_names: ["XTen", "XTen Systems", "XTen Group"],
      entity_type: "Australian Private Company",
      status: "Active (GST Registered)",
      gst_registered: true,
      registered_since: "2014-10-15",
      anzsic_code: "7000",
      anzsic_division: "M",
      anzsic_class: "Computer System Design and Related Services",
      state: "WA",
      suburb: "Perth",
      postcode: "6000",
      address: "St Georges Terrace, Perth WA 6000",
      phone: "(08) 6555 6897",
      email: "directory@xten.au",
      website: "https://xten.au",
      is_peppol_ready: true,
      peppol_id: "0151:38602365346",
      verified: true,
      claimed: true,
      tier: "prominent",
      has_video: true,
      video_duration: "0:30",
      video_title: "XTen Systems — Engineering Autonomous Business Platforms",
      views_this_month: 1420,
      description: "Australian software systems engineering company delivering modular business software platforms, disaster recovery audits, autonomous agent operations, and national commercial registry services."
    },
    {
      id: "comp-xten-2",
      abn: "38602365346",
      acn: "602365346",
      name: "XTen.Stack",
      trading_names: ["XTen Stack", "Stack Platform", "stack.xten.au"],
      entity_type: "Commercial Software Product / Enterprise Framework",
      status: "Active (Production Platform)",
      gst_registered: true,
      registered_since: "2024-01-01",
      anzsic_code: "7000",
      anzsic_division: "M",
      anzsic_class: "Software Publishing and Enterprise Applications",
      state: "WA",
      suburb: "Perth",
      postcode: "6000",
      address: "St Georges Terrace, Perth WA 6000",
      phone: "(08) 6555 6897",
      email: "directory@xten.au",
      website: "https://stack.xten.au",
      verified: true,
      claimed: true,
      tier: "featured",
      views_this_month: 2840,
      description: "Open-source, security-first PHP 8.3 & PostgreSQL modular application platform. Ships 80% complete with multi-tenant RBAC, audit logging, ticketing, and compliance."
    },
    {
      id: "comp-xten-3",
      abn: "38602365346",
      acn: "602365346",
      name: "XTen.Deploy",
      trading_names: ["XTen Deploy", "deploy.xten.au", "Deploy Custom Engineering"],
      entity_type: "Cloud Architecture & Custom Engineering Service",
      status: "Active (Production Delivery)",
      gst_registered: true,
      registered_since: "2024-01-01",
      anzsic_code: "7000",
      anzsic_division: "M",
      anzsic_class: "Cloud Infrastructure and Deployment Services",
      state: "WA",
      suburb: "Perth",
      postcode: "6000",
      address: "St Georges Terrace, Perth WA 6000",
      phone: "(08) 6555 6897",
      email: "directory@xten.au",
      website: "https://deploy.xten.au",
      verified: true,
      claimed: true,
      tier: "featured",
      views_this_month: 1980,
      description: "Fixed-price custom business software design, cloud architecture, automated DevOps deployments, and autonomous support agent integration on XTen.Stack."
    },
    {
      id: "comp-xten-4",
      abn: "38602365346",
      acn: "602365346",
      name: "XTen.Register (Commercial Directory)",
      trading_names: ["XTen National Business Register", "directory.xten.au"],
      entity_type: "National Business & Statutory Registry Service",
      status: "Active (Official Public Register)",
      gst_registered: true,
      registered_since: "2026-09-01",
      anzsic_code: "7000",
      anzsic_division: "M",
      anzsic_class: "Internet Publishing and Business Information Services",
      state: "WA",
      suburb: "Perth",
      postcode: "6000",
      address: "St Georges Terrace, Perth WA 6000",
      phone: "(08) 6555 6897",
      email: "directory@xten.au",
      website: "https://directory.xten.au",
      verified: true,
      claimed: true,
      tier: "prominent",
      has_video: true,
      video_duration: "0:30",
      video_title: "XTen National Register — Australian Business & Entity Directory",
      views_this_month: 8950,
      description: "Australia's open programmatic commercial directory indexing 2.5M registered companies, ABNs, ACNs, and corporate due diligence intelligence."
    },
    {
      id: "comp-assn-1",
      abn: "",
      association_number: "IARN-WA-A100482",
      name: "Swan River Amateur Yachting & Community Society",
      trading_names: ["Swan River Yachting", "SRAYC Community"],
      entity_type: "Incorporated Association (Not-for-profit)",
      status: "Active (WA Associations Act 2015)",
      gst_registered: false,
      registered_since: "1998-03-12",
      anzsic_code: "9139",
      anzsic_division: "R",
      anzsic_class: "Sporting and Physical Recreation Clubs",
      state: "WA",
      suburb: "Nedlands",
      postcode: "6009",
      address: "The Broadway, Nedlands WA 6009",
      phone: "(08) 9386 1234",
      email: "secretary@swanriveryachting.org.au",
      website: "https://swanriveryachting.org.au",
      verified: true,
      claimed: true,
      tier: "featured",
      views_this_month: 512,
      description: "Volunteer-run community sailing society and junior training club operating under the WA Associations Incorporation Act 2015. Non-profit sporting association exempt from ABN requirements."
    },
    {
      id: "comp-1",
      abn: "78268981692",
      acn: "108394821",
      name: "Adelaide Paediatrics Pty Ltd",
      trading_names: ["Adelaide Paediatrics", "Adelaide Child Health Care"],
      entity_type: "Australian Private Company",
      status: "Active (GST Registered)",
      gst_registered: true,
      registered_since: "2011-04-14",
      anzsic_code: "8512",
      anzsic_division: "Q",
      anzsic_class: "Specialist Medical Services",
      state: "SA",
      suburb: "Kensington Park",
      postcode: "5068",
      address: "148 The Parade, Kensington Park SA 5068",
      phone: "(08) 7123 6177",
      email: "reception@adelaidepaediatrics.com.au",
      website: "https://www.adelaidepaediatrics.com.au",
      is_peppol_ready: true,
      peppol_id: "0151:78268981692",
      verified: true,
      claimed: true,
      tier: "prominent",
      has_video: true,
      video_duration: "0:28",
      video_title: "Meet Our Multi-Disciplinary Paediatric Clinical Team",
      views_this_month: 482,
      description: "Comprehensive multi-disciplinary paediatric healthcare clinic providing specialist consultations, developmental assessments, and allied health support across South Australia."
    },
    {
      id: "comp-2",
      abn: "11000000948",
      acn: "000000948",
      name: "QBE Insurance (International) Limited",
      trading_names: ["QBE Australia", "QBE Insurance Group"],
      entity_type: "Australian Public Company",
      status: "Active (GST Registered)",
      gst_registered: true,
      registered_since: "1970-01-01",
      anzsic_code: "6322",
      anzsic_division: "K",
      anzsic_class: "General Insurance",
      state: "NSW",
      suburb: "Sydney",
      postcode: "2000",
      address: "Level 18, 388 George Street, Sydney NSW 2000",
      phone: "133 723",
      email: "contact@qbe.com.au",
      website: "https://www.qbe.com.au",
      is_peppol_ready: true,
      peppol_id: "0151:11000000948",
      verified: true,
      claimed: true,
      views_this_month: 2319,
      description: "Leading international general insurance and reinsurance provider, offering commercial, business, and personal insurance solutions."
    },
    {
      id: "comp-3",
      abn: "40006247016",
      acn: "006247016",
      name: "Regional Publishers (Western Victoria) Pty Limited",
      trading_names: ["The Courier", "Western Media Group"],
      entity_type: "Australian Private Company",
      status: "Active (GST Registered)",
      gst_registered: true,
      registered_since: "1984-06-12",
      anzsic_code: "5411",
      anzsic_division: "J",
      anzsic_class: "Newspaper Publishing",
      state: "VIC",
      suburb: "Ballarat",
      postcode: "3350",
      address: "8 Trench Street, Ballarat VIC 3350",
      phone: "(03) 5320 1200",
      email: "editorial@thecourier.com.au",
      website: "https://www.thecourier.com.au",
      is_peppol_ready: true,
      peppol_id: "0151:40006247016",
      verified: true,
      claimed: false,
      views_this_month: 154,
      description: "Regional community news publication and digital news provider serving Ballarat and the Western Victorian region."
    },
    {
      id: "comp-4",
      abn: "51824753556",
      acn: "",
      name: "Australian Taxation Office",
      trading_names: ["ATO", "Australian Tax Office"],
      entity_type: "Commonwealth Government Entity",
      status: "Active (Exempt)",
      gst_registered: true,
      registered_since: "1999-11-01",
      anzsic_code: "7510",
      anzsic_division: "O",
      anzsic_class: "Central Banking and Monetary Authority",
      state: "ACT",
      suburb: "Canberra",
      postcode: "2600",
      address: "26 Nishi Commercial, 2 Phillip Law St, Canberra ACT 2601",
      phone: "13 28 61",
      email: "enquiries@ato.gov.au",
      website: "https://www.ato.gov.au",
      verified: true,
      claimed: true,
      views_this_month: 12450,
      description: "The statutory revenue collection agency of the Australian Government responsible for administering the federal taxation and superannuation systems."
    },
    {
      id: "comp-5",
      abn: "95000075025",
      acn: "000075025",
      name: "Illawarra Newspapers Holdings Pty Ltd",
      trading_names: ["Illawarra Mercury", "South Coast Media"],
      entity_type: "Australian Private Company",
      status: "Active (GST Registered)",
      gst_registered: true,
      registered_since: "1988-02-18",
      anzsic_code: "5411",
      anzsic_division: "J",
      anzsic_class: "Newspaper Publishing",
      state: "NSW",
      suburb: "Wollongong",
      postcode: "2500",
      address: "282 Keira Street, Wollongong NSW 2500",
      phone: "(02) 4221 2333",
      email: "news@illawarramercury.com.au",
      website: "https://www.illawarramercury.com.au",
      verified: true,
      claimed: false,
      views_this_month: 189,
      description: "Daily regional newspaper and online news service delivering South Coast local community reporting and classified advertisements."
    },
    {
      id: "comp-6",
      abn: "11126884786",
      acn: "126884786",
      name: "HBF Health Limited",
      trading_names: ["HBF", "HBF Health Insurance"],
      entity_type: "Australian Public Company",
      status: "Active (GST Registered)",
      gst_registered: true,
      registered_since: "2007-08-01",
      anzsic_code: "6321",
      anzsic_division: "K",
      anzsic_class: "Health Insurance",
      state: "WA",
      suburb: "Perth",
      postcode: "6000",
      address: "570 Wellington Street, Perth WA 6000",
      phone: "133 423",
      email: "memberexperience@hbf.com.au",
      website: "https://www.hbf.com.au",
      verified: true,
      claimed: true,
      views_this_month: 3820,
      description: "Western Australia's leading not-for-profit health insurance provider providing hospital, medical, and ancillary cover across Australia."
    },
    {
      id: "comp-7",
      abn: "38602365346",
      acn: "602365346",
      name: "XTen Systems Pty Ltd",
      trading_names: ["XTen", "XTen.Stack", "XTen.Deploy"],
      entity_type: "Australian Private Company",
      status: "Active (GST Registered)",
      gst_registered: true,
      registered_since: "2014-10-15",
      anzsic_code: "7000",
      anzsic_division: "M",
      anzsic_class: "Computer System Design and Related Services",
      state: "WA",
      suburb: "Perth",
      postcode: "6000",
      address: "St Georges Terrace, Perth WA 6000",
      phone: "(08) 6555 6897",
      email: "directory@xten.au",
      website: "https://xten.au",
      verified: true,
      claimed: true,
      tier: "featured",
      views_this_month: 940,
      description: "Specialist Australian software systems engineering company providing secure modular business application platforms, disaster recovery audits, and autonomous support agents."
    },
    {
      id: "comp-8",
      abn: "84128912833",
      acn: "128912833",
      name: "Apex Electrical Contractors Pty Ltd",
      trading_names: ["Apex Electrical & Solar"],
      entity_type: "Australian Private Company",
      status: "Active (GST Registered)",
      gst_registered: true,
      registered_since: "2015-09-22",
      anzsic_code: "3232",
      anzsic_division: "E",
      anzsic_class: "Electrical Services",
      state: "QLD",
      suburb: "Brisbane",
      postcode: "4000",
      address: "Level 4, 120 Edward Street, Brisbane QLD 4000",
      phone: "(07) 3892 1100",
      email: "contact@apexelectrical.com.au",
      website: "https://apexelectrical.com.au",
      verified: false,
      claimed: false,
      views_this_month: 96,
      description: "Commercial and industrial electrical engineering, switchboard design, high-voltage cabling, and commercial solar installations across South East Queensland."
    }
  ],

  people: [
    {
      id: "ppl-xten-5",
      abn: "38602365346",
      full_name: "XTen.Register (People & Professionals)",
      profession: "National Practitioner & Verified Professional Directory",
      business_name: "XTen Systems Pty Ltd",
      entity_type: "National Professional Registry Service",
      status: "Active (Official Public Register)",
      registered_since: "2026-09-01",
      category: "Professional Services & Practitioners",
      state: "WA",
      suburb: "Perth",
      postcode: "6000",
      clinic_address: "St Georges Terrace, Perth WA 6000",
      phone: "(08) 6555 6897",
      email_proxy: "directory@xten.au",
      verified: true,
      claimed: true,
      tier: "prominent",
      has_video: true,
      video_duration: "0:30",
      video_title: "XTen.Register — Discover & Verify Australian Practitioners",
      views_this_month: 7420,
      bio: "Australia's open programmatic practitioner directory indexing sole traders, accredited clinical specialists, licensed trades, and consulting professionals cross-verified against ABN, ASIC, and industry credentials."
    },
    {
      id: "ppl-1",
      abn: "27914471446",
      full_name: "Laura Freer",
      profession: "Accredited Practising Dietitian (APD)",
      business_name: "Laura Freer Dietetics",
      entity_type: "Individual / Sole Trader",
      status: "Active (Registered Practitioner)",
      registered_since: "2018-05-10",
      category: "Allied Health Services",
      state: "SA",
      suburb: "Norwood",
      postcode: "5067",
      clinic_address: "Consulting at Adelaide Paediatrics, Norwood SA",
      phone: "(08) 7123 6177",
      email_proxy: "l.freer@adelaidepaediatrics.com.au",
      verified: true,
      claimed: true,
      tier: "featured",
      views_this_month: 312,
      bio: "Paediatric and adolescent clinical dietitian specialising in food allergies, paediatric growth faltering, enteral nutrition, and gut microbiome health."
    },
    {
      id: "ppl-2",
      abn: "53357080021",
      full_name: "Rachel George",
      profession: "Senior Paediatric Speech Pathologist",
      business_name: "Rachel George Speech Therapy",
      entity_type: "Individual / Sole Trader",
      status: "Active (Registered Practitioner)",
      registered_since: "2017-02-14",
      category: "Speech Pathology",
      state: "SA",
      suburb: "Morphett Vale",
      postcode: "5162",
      clinic_address: "Consulting Suites, Morphett Vale SA 5162",
      phone: "(08) 7123 6188",
      email_proxy: "r.george@adelaidepaediatrics.com.au",
      verified: true,
      claimed: false,
      views_this_month: 185,
      bio: "Speech pathologist providing diagnostic speech assessments, early language intervention, augmentative communication, and childhood literacy support."
    },
    {
      id: "ppl-3",
      abn: "41737017378",
      full_name: "Dr Anthony Chitti",
      profession: "Consultant Paediatrician",
      business_name: "Dr Anthony Chitti Medical Services",
      entity_type: "Individual / Sole Trader",
      status: "Active (AHPRA Registered)",
      registered_since: "2009-08-20",
      category: "Medical Specialists",
      state: "SA",
      suburb: "Kensington Park",
      postcode: "5068",
      clinic_address: "148 The Parade, Kensington Park SA 5068",
      phone: "(08) 7123 6177",
      email_proxy: "reception@adelaidepaediatrics.com.au",
      verified: true,
      claimed: true,
      tier: "prominent",
      has_video: true,
      video_duration: "0:30",
      video_title: "Paediatric Developmental Care & Clinical Services Tour",
      views_this_month: 624,
      bio: "General and developmental paediatrician with special interest in ADHD, autism spectrum disorders, neonatal medicine, and paediatric chronic illness."
    },
    {
      id: "ppl-4",
      abn: "94337931054",
      full_name: "Sharon Price",
      profession: "Clinical Audiologist (MAudSA CCP)",
      business_name: "Sharon Price Audiology",
      entity_type: "Individual / Sole Trader",
      status: "Active (Audiology Australia Accredited)",
      registered_since: "2015-11-03",
      category: "Audiology & Hearing",
      state: "SA",
      suburb: "North Adelaide",
      postcode: "5006",
      clinic_address: "Melbourne Street Medical Centre, North Adelaide SA",
      phone: "(08) 8267 1144",
      email_proxy: "contact@audsa.com.au",
      verified: false,
      claimed: false,
      views_this_month: 92,
      bio: "Specialist paediatric audiologist conducting visual reinforcement audiometry, otoacoustic emission testing, and auditory processing disorder evaluations."
    },
    {
      id: "ppl-5",
      abn: "32513498572",
      full_name: "David Stampfli",
      profession: "Commercial Architectural Photographer",
      business_name: "David Stampfli Photography",
      entity_type: "Individual / Sole Trader",
      status: "Active (AIPP Accredited)",
      registered_since: "2016-03-29",
      category: "Creative & Media",
      state: "NSW",
      suburb: "Surry Hills",
      postcode: "2010",
      clinic_address: "Surry Hills Creative Hub, Sydney NSW",
      phone: "0412 884 122",
      email_proxy: "craig@stampfli.photography",
      verified: true,
      claimed: true,
      views_this_month: 277,
      bio: "Specialising in high-end commercial architecture, interior design photography, civil infrastructure documentation, and corporate brand imagery."
    },
    {
      id: "ppl-6",
      abn: "18229904193",
      full_name: "Marcus Vance",
      profession: "Licensed Electrical Contractor (Lic #EC012488)",
      business_name: "Vance Power & Data",
      entity_type: "Individual / Sole Trader",
      status: "Active (Licensed Electrical Tradesperson)",
      registered_since: "2014-07-19",
      category: "Building & Construction Trades",
      state: "WA",
      suburb: "Subiaco",
      postcode: "6008",
      clinic_address: "Rokeby Road, Subiaco WA 6008",
      phone: "0401 559 312",
      email_proxy: "marcus@vancepower.com.au",
      verified: true,
      claimed: false,
      views_this_month: 340,
      bio: "Master electrician offering commercial office fit-outs, emergency power installations, structured Cat6A data cabling, and smart home energy automation."
    }
  ]
};

const EXPANDED_PROFESSIONS = [
  "All Professions",
  "Accounting & Tax: Registered Tax Agent (6932)",
  "Accounting & Tax: Registered BAS Agent (6932)",
  "Accounting & Tax: Certified Bookkeeper (6932)",
  "Finance: Financial Planner & Wealth Adviser (6411)",
  "Finance: Mortgage Broker & Credit Representative (6419)",
  "Finance: Licensed Credit Provider & Non-Bank Lender (6229)",
  "Finance: Insurance Broker (6310)",
  "Legal: Solicitor & Legal Practitioner (6931)",
  "Legal: Barrister (6931)",
  "Legal: Licensed Conveyancer (6931)",
  "Legal: Registered Migration Agent (6931)",
  "Health: General Practitioner (GP) (8511)",
  "Health: Dentist & Dental Specialist (8531)",
  "Health: Physiotherapist (8539)",
  "Health: Clinical Psychologist (8539)",
  "Health: Pharmacist (4271)",
  "Health: Chiropractor (8539)",
  "Health: Podiatrist (8539)",
  "Health: Optometrist (8532)",
  "Health: Occupational Therapist (8539)",
  "Health: Audiologist & Hearing Specialist (8539)",
  "Trades: Licensed Electrical Contractor (3232)",
  "Trades: Master Electrician (3232)",
  "Trades: Licensed Plumber & Drainer (3231)",
  "Trades: Licensed Gasfitter (3231)",
  "Trades: Master Builder & Principal Contractor (3011)",
  "Trades: Carpenter & Joiner (3242)",
  "Trades: HVAC & Air Conditioning Specialist (3233)",
  "Trades: Painter & Decorator (3244)",
  "Trades: Roof Plumber & Restoration (3231)",
  "Trades: Licensed Land Surveyor (6922)",
  "Trades: Building Certifier & Inspector (6923)",
  "Property: Licensed Real Estate Agent (6720)",
  "Property: Residential Property Manager (6720)",
  "Property: Commercial Property Broker (6720)",
  "Property: Strata & Body Corporate Manager (6720)",
  "Property: Certified Practising Valuer (6720)",
  "Tech & Design: Consulting Engineer (6923)",
  "Tech & Design: IT Consultant & Cloud Architect (7000)",
  "Tech & Design: Software & App Developer (5420)",
  "Tech & Design: Cybersecurity Specialist (7000)",
  "Tech & Design: Commercial Architectural Photographer (6991)",
  "Tech & Design: Graphic & Digital Designer (6924)",
  "Community & Care: Registered NDIS Provider & Coordinator (8790)",
  "Community & Care: Disability Support Specialist (8790)",
  "Community & Care: Personal Fitness Trainer & Coach (9111)",
  "Community & Care: Veterinary Surgeon & Clinician (6970)"
];

const EXPANDED_INDUSTRIES = [
  "All Industries",
  "Charities & Non-Profit: Registered Public Benevolent Institution (PBI) (9559)",
  "Charities & Non-Profit: Health & Medical Foundations (9559)",
  "Charities & Non-Profit: Community Welfare & Relief Services (9559)",
  "Charities & Non-Profit: Education & Youth Advancement (9559)",
  "Construction: Residential Building Construction (3011)",
  "Construction: Commercial & Non-Residential Construction (3020)",
  "Construction: Electrical Services & Contracting (3232)",
  "Construction: Plumbing & Gasfitting Services (3231)",
  "Construction: Air Conditioning & Heating Services (3233)",
  "Construction: Carpentry & Joinery Services (3242)",
  "Construction: Painting & Decorating Services (3244)",
  "Finance: Financial Planning & Investment Advice (6411)",
  "Finance: Mortgage Broking & Credit Advisory (6419)",
  "Finance: Credit Provider & Non-Bank Lending (6229)",
  "Finance: General & Life Insurance (6310)",
  "Professional Services: Legal Services & Law Firms (6931)",
  "Professional Services: Accounting & Tax Services (6932)",
  "Professional Services: Architectural Services (6921)",
  "Professional Services: Engineering Design & Consulting (6923)",
  "Professional Services: Management & Business Consulting (6962)",
  "Professional Services: Advertising & Digital Marketing (6940)",
  "Healthcare: General Practice Medical Clinics (8511)",
  "Healthcare: Specialist Medical Clinics & Day Surgery (8512)",
  "Healthcare: Dental Practices & Laboratories (8531)",
  "Healthcare: Physiotherapy & Allied Health Clinics (8539)",
  "Healthcare: NDIS & Disability Support Services (8790)",
  "Technology: Computer System Design & Cloud Infrastructure (7000)",
  "Technology: Software Publishing & SaaS Platforms (5420)",
  "Technology: Telecommunications Network Operations (5801)",
  "Property: Real Estate Agencies & Property Management (6720)",
  "Property: Commercial Property Investment & Leasing (6712)",
  "Hospitality: Cafes and Restaurants (4511)",
  "Hospitality: Takeaway Food & Beverage Services (4512)",
  "Hospitality: Accommodation & Boutique Hotels (4400)",
  "Manufacturing: Food & Beverage Processing (1111)",
  "Manufacturing: Metal Fabrication & Precision Engineering (2221)",
  "Manufacturing: Machinery & Industrial Equipment (2412)",
  "Wholesale: Machinery & Electronic Equipment Wholesaling (3492)",
  "Transport: Road Freight & Courier Transport (4610)",
  "Transport: Warehousing & Cold Storage Logistics (5301)"
];
